[package]
name = "pg_dig_server"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.169"
scroll = {  version = "0.12.0", features = ["derive"] }
memoffset = "0.9.1"
chrono = "0.4.39"

[build-dependencies]
bindgen = "0.71.0"
