[package]
name = "pg_dig_server"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.6.0"
bevy = "0.15.1"
scroll = { version = "0.12.0", features = ["derive"] }
log = "0.4.22"
phf = { version = "0.11.3", features = ["macros"] }
[build-dependencies]
bindgen = "0.71.0"
